export default contact = [
  {
    id: "1",
    fname: "Trần Phương",
    lname: "Duy",
    cardNumber: "0987 3422 8756",
    bank: "MB",
    source: require("../../assets/images/img1.jpg"),
  },
  {
    id: "2",
    fname: "Lê Đại",
    lname: "Dương",
    cardNumber: "2459 9561 7815",
    bank: "BIDV",
    source: require("../../assets/images/img2.jpg"),
  },
  {
    id: "3",
    fname: "Thẩm Minh",
    lname: "Đức",
    cardNumber: "4651 9457 5555",
    bank: "OCB",
    source: require("../../assets/images/img3.jpg"),
  },
  {
    id: "4",
    fname: "Đặng Ngọc",
    lname: "Duy",
    cardNumber: "7891 3359 6655",
    bank: "MB",
    source: require("../../assets/images/img4.jpg"),
  },
  {
    id: "5",
    fname: "Nguyễn Thành",
    lname: "Đạt",
    cardNumber: "0987 8769 6412",
    bank: "OCB",
    source: require("../../assets/images/img5.jpeg"),
  },
  {
    id: "6",
    fname: "John",
    lname: "Doe",
    cardNumber: "0987 3422 8756",
    bank: "MB",
    source: require("../../assets/images/img6.jpg"),
  },
  {
    id: "7",
    fname: "David",
    lname: "Villa",
    cardNumber: "0987 8756 3336",
    bank: "MB",
    source: require("../../assets/images/img7.jpg"),
  },
  {
    id: "8",
    fname: "Nguyễn",
    lname: "Hoàng",
    cardNumber: "0987 3422 8756",
    bank: "BIDV",
    source: require("../../assets/images/sang.jpg"),
  },
];
